### ISSUE TITLE
您好，我想问下有没有安卓开源播放器的项目

### ISSUE THREAD

**Issue by rewatn** [zhaoolee/StarsAndClown#1]
是这样的，我想让我家的智能大屏电视播放我电脑上的电影，不知道有什么好的解决办法，win10系统

**Comment by myd7349** [comment]
https://github.com/xbmc/xbmc

**Comment by rewatn** [comment]
> https://github.com/xbmc/xbmc
> https://github.com/videolan/vlc

谢谢，都是很庞大的项目，xbmc已经研究好装在我家大电视上
